# Generated by Django 4.2.11 on 2024-04-15 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0003_booking_email_booking_hotel_booking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookhotel', to='hotelbooking.hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookroom', to='hotelbooking.room'),
        ),
    ]
