# Generated by Django 4.2.11 on 2024-04-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0004_booking_hotel_name_booking_room_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
