# Generated by Django 4.2.11 on 2024-04-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0005_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='forgot_password_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
